refactor: fcard refactored to Composition API (refs SFKUI-6500)
Forsakringskassan/designsystem pull request #67
Opened 2024-10-09 11:33 UTC by KrQnan66140124

Refactor FCard to composition API

2024-10-09 12:50 UTC, dvitamin requested changes

2024-10-09 12:50 UTC, dvitamin commented on packages/vue/src/components/FCard/FCard.vue
> +const headingClass = ref(["card__header-label"]);
Lägga värdet direkt i templaten?

2024-10-09 12:50 UTC, dvitamin commented on packages/vue/src/components/FCard/FCard.vue
> -            return hasSlot(this, "header");
`hasSlot` behövs fortfarande för att det ska fungera med nästlade slots (en komponent som exponerar en slot ned till denna slotten). Vi saknar unittest för det i nuläget och det är inte speciellt tydligt.

Du kan anropa den med 
`hasSlot({ $slots }, "header" })`

2024-10-09 13:29 UTC, ext commented on packages/vue/src/components/FCard/FCard.vue
> -            return hasSlot(this, "header");
Diskuterat lite med @dvitamin och ovan är en bra workaround för att komma vidare.

I framtiden ser vi nog att man skapar en composable likt:

```ts
function useSlotUtils() {
    const $slots = useSlots(); // från vue
    return {
        hasSlot(name: string) {
            return hasSlot({ $slots }, name); // dvs vi kapslar in workarounden från ovan
       },
    };
}
```

och används då som:

```ts
const { hasSlot } = useSlotUtils();
const hasHeaderSlot = computed(() => hasSlot("header"));
```

2024-10-09 13:45 UTC, KrQnan66140124 commented on packages/vue/src/components/FCard/FCard.vue
> -            return hasSlot(this, "header");
Absolut det kan jag testa

2024-10-10 08:44 UTC, KrQnan66140124 commented
@ext @dvitamin Uppdaterat filerna med lite nytt :)

2024-10-11 07:07 UTC, ext approved these changes

2024-10-14 12:49 UTC, dvitamin approved these changes

2024-10-14 12:49 UTC, dvitamin commented on packages/vue/src/components/FCard/FCard.vue
> +            <slot name="header" class="card__header-label"></slot>
```suggestion
            <slot name="header" v-bind="{ headingSlotClass: 'card__header-label' }"></slot>
```

- [ ] skicka med enligt förslag i scoped slot

2024-11-06 12:05 UTC, NicklasWei submitted a review, later dismissed

2024-11-06 12:24 UTC, MCFK submitted a review, later dismissed

2024-11-27 23:17 UTC, ext approved these changes

2024-11-27 23:26 UTC, merged